### ISSUE TITLE
Missing dependency: ZMQ

### ISSUE THREAD

**Issue by pedronahum** [facebookresearch/starcraft_defogger#1]
Hi,

First and foremost, thank you for making the code available. 

Just in case someone runs into my same issue (Ubuntu 18.04.1 LTS):

```
client/../BWEnv/include/zmq.hpp:42:10: fatal error: zmq.h: No such file or directory
```

This can be solved by:

```
sudo apt-get install libzmq3-dev
```
The ``` zeromq 4+ ``` dependency, however, is mentioned in the TorchCraft repo. 

Best,

**Comment by ebetica** [comment]
Thanks for the update, I will add it to the readme.
