### ISSUE TITLE
Data links

### ISSUE THREAD

**Issue by pedronahum** [facebookresearch/starcraft_defogger#3]
Hi,

The link to ``` https://s3-us-west-2.amazonaws.com/stardata/defogger_reduced_aiide17.tar.gz ``` produces the following error:
``` 
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>69215262E0A47C18</RequestId>
<HostId>BCNWWXuvra3lHP5UvfHA/wvypo4rYXHyJx/VJ2W6/xpKbkWt0Y1KzJFHXyb3dkreBu7arUW7UOg=</HostId>
</Error>
``` 

And the "Download the dataset" link is pointing to "original_replays". And was wondering if you wanted to link to the "defogger_reduced.tar.gz" file instead. 

Thanks,

**Comment by ebetica** [comment]
I think the link is correct, but I failed to make it public. I asserted that it now works. Good luck!
