### ISSUE TITLE
Train, Valid, and Test lists

### ISSUE THREAD

**Issue by pedronahum** [facebookresearch/starcraft_defogger#4]
Hi,

Hope you can, once again, point me in the right direction :o)

The code is referencing several lists (train.list, valid.list, test.list, and smalltrain.list). The "smalltrain.list" is needed, for example, to perform the basic test "does it work?". These lists, however, are not part of the "original_replays.tar.gz" file. 

You do have made available/public in S3 a train.list, a valid.list, and a test.list, but these are referencing .tcr files. Yet the "original_replays" are ".rep"; so either the "original_replays" file is before pre-processing or these lists are just missing (or, of course, I could be doing something very wrong).  

Any pointer here is greatly appreciated. 

Thanks,

**Comment by ebetica** [comment]
Ah I apologize, but you can generate the small lists simply by doing:

```
head -n100 train.list > smalltrain.list
head -n100 valid.list > smallvalid.list
head -n100 test.list > smalltest.list
```

I realized I provided the wrong link for the download... So sorry for using up your bandwidth! The correct link is [here](https://s3-us-west-2.amazonaws.com/stardata/defogger_reduced.tar.gz). These are the data files after preprocessing the .tcr replay files. The explaination is that the .rep is a list of commands, which we replay back in the simulator (StarCraft) to get .tcr files, which are the full list of units, bullets, at every frame. Then, we do the coarse resolution downsampling as described in the paper to further reduce the dataset size to the 53 GB in the above link.

**Comment by pedronahum** [comment]
Hi @ebetica,
Many thanks for getting back me. No worries, I can confirm that the link is public and README is now updated :o)
This will now keep me busy. Have a nice day!

**Comment by pedronahum** [comment]
Hi @ebetica 

I think we can close this ticket. The new link one can run the code. 

Thanks again for your help! Happy holidays
